FROM python:3.8-slim-buster

# Copy everything on current root directory to /app directory
COPY . /app 

# Install needed libraries to run the scripts
COPY requirements.txt /app/requirements.txt

# Give running permissions
RUN chmod +x /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Expose port 5000
EXPOSE 5000 

# Set some environment variables. PYTHONUNBUFFERED keeps Python from buffering out standard
# output stream, which means that logs can be delivered to the user quickly. 
# PYTHONDONTWRITEBYTECODE keeps Python from writing the .pyc files, which are unnecessary in this case
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PYTHONIOENCODING=UTF-8
WORKDIR /app

CMD ["python", "app.py"]